hf_configuration:
  hf_dataset_name: nasa_sp287_example # change this to your desired dataset name
  private: false # change this to true if you want to make the dataset private. it's true by default.

model_list:
  - model_name: Qwen/Qwen3-30B-A3B
    provider: fireworks-ai

pipeline:
  ingestion:
    source_documents_dir: example/data/nasa_raw
    output_dir: example/data/nasa_processed
  upload_ingest_to_hub:
  summarization:
  chunking:
  single_shot_question_generation:
  multi_hop_question_generation:
  lighteval:
  citation_score_filtering: