hf_configuration:
  hf_dataset_name: nasa_sp287_example_gpt # change this to your desired dataset name
  private: false # change this to true if you want to make the dataset private. it's true by default.

model_list:
  - model_name: gpt-4.1-nano
    base_url: https://api.openai.com/v1
    api_key: $OPENAI_API_KEY
    max_concurrent_requests: 8

pipeline:
  ingestion:
    source_documents_dir: example/data/nasa_raw
    output_dir: example/data/nasa_processed
  upload_ingest_to_hub:
  summarization:
  chunking:
  single_shot_question_generation:
  multi_hop_question_generation:
  lighteval:
  citation_score_filtering: